<?php

namespace ContainerB4YBsgf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTotalService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\total' shared autowired service.
     *
     * @return \App\Service\total
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'total.php';

        return $container->privates['App\\Service\\total'] = new \App\Service\total();
    }
}
