<?php

namespace Container5gk3N4b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_7MNwHrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.7M_NwHr' shared service.
     *
     * @return \App\Service\total
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\UserController::panierUser()": the $total argument is type-hinted with the non-existent class or interface: "App\\Service\\total".');
    }
}
