<?php

namespace Container5gk3N4b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FGb9pw3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fGb9pw3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fGb9pw3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::deleteUser' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\AdminController::editUser' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\AdminController::usersList' => ['privates', '.service_locator.QOjUGpS', 'get_ServiceLocator_QOjUGpSService', true],
            'App\\Controller\\ProduitController::productList' => ['privates', '.service_locator.6bIMjA9', 'get_ServiceLocator_6bIMjA9Service', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.gPh6X_L', 'get_ServiceLocator_GPh6XLService', true],
            'App\\Controller\\SiteController::add' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\SiteController::del' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController::deleteProduct' => ['privates', '.service_locator.8XUY8CO', 'get_ServiceLocator_8XUY8COService', true],
            'App\\Controller\\UserController::editUser' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController::editUser2' => ['privates', '.service_locator.PCa85Br', 'get_ServiceLocator_PCa85BrService', true],
            'App\\Controller\\UserController::panierUser' => ['privates', '.service_locator.I7vGXmc', 'get_ServiceLocator_I7vGXmcService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminController:deleteUser' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\AdminController:editUser' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\AdminController:usersList' => ['privates', '.service_locator.QOjUGpS', 'get_ServiceLocator_QOjUGpSService', true],
            'App\\Controller\\ProduitController:productList' => ['privates', '.service_locator.6bIMjA9', 'get_ServiceLocator_6bIMjA9Service', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.gPh6X_L', 'get_ServiceLocator_GPh6XLService', true],
            'App\\Controller\\SiteController:add' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\SiteController:del' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController:deleteProduct' => ['privates', '.service_locator.8XUY8CO', 'get_ServiceLocator_8XUY8COService', true],
            'App\\Controller\\UserController:editUser' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController:editUser2' => ['privates', '.service_locator.PCa85Br', 'get_ServiceLocator_PCa85BrService', true],
            'App\\Controller\\UserController:panierUser' => ['privates', '.service_locator.I7vGXmc', 'get_ServiceLocator_I7vGXmcService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminController::deleteUser' => '?',
            'App\\Controller\\AdminController::editUser' => '?',
            'App\\Controller\\AdminController::usersList' => '?',
            'App\\Controller\\ProduitController::productList' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Controller\\SiteController::add' => '?',
            'App\\Controller\\SiteController::del' => '?',
            'App\\Controller\\UserController::deleteProduct' => '?',
            'App\\Controller\\UserController::editUser' => '?',
            'App\\Controller\\UserController::editUser2' => '?',
            'App\\Controller\\UserController::panierUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:deleteUser' => '?',
            'App\\Controller\\AdminController:editUser' => '?',
            'App\\Controller\\AdminController:usersList' => '?',
            'App\\Controller\\ProduitController:productList' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'App\\Controller\\SiteController:add' => '?',
            'App\\Controller\\SiteController:del' => '?',
            'App\\Controller\\UserController:deleteProduct' => '?',
            'App\\Controller\\UserController:editUser' => '?',
            'App\\Controller\\UserController:editUser2' => '?',
            'App\\Controller\\UserController:panierUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
