<?php

namespace Container5gk3N4b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I7vGXmcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I7vGXmc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I7vGXmc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'total' => ['privates', '.errored.7M_NwHr', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::panierUser()": the $total argument is type-hinted with the non-existent class or interface: "App\\Service\\total".'],
            'user' => ['privates', '.errored..service_locator.I7vGXmc.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.I7vGXmc": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'total' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
