<?php

namespace ContainerGxCECaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ow64Yd0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ow64Yd0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ow64Yd0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'products' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
            'test' => ['privates', '.errored.ClbAbLL', NULL, 'Cannot determine controller argument for "App\\Controller\\ProduitController::productList()": the $test argument is type-hinted with the non-existent class or interface: "App\\Repository\\PanierRepository".'],
            'user' => ['privates', '.errored..service_locator.Ow64Yd0.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.Ow64Yd0": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'products' => 'App\\Repository\\ProduitRepository',
            'test' => '?',
            'user' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
        ]);
    }
}
