<?php

namespace ContainerGxCECaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FWBHCpDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FWBHCpD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FWBHCpD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'panier' => ['privates', '.errored.Ew8xs18', NULL, 'Cannot determine controller argument for "App\\Controller\\ProduitController::affichePanier()": the $panier argument is type-hinted with the non-existent class or interface: "App\\Repository\\PanierRepository".'],
            'user' => ['privates', '.errored..service_locator.FWBHCpD.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.FWBHCpD": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'panier' => '?',
            'user' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
        ]);
    }
}
