<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTHFv6xf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTHFv6xf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTHFv6xf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTHFv6xf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTHFv6xf\App_KernelDevDebugContainer([
    'container.build_hash' => 'THFv6xf',
    'container.build_id' => 'db8c868b',
    'container.build_time' => 1618493008,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTHFv6xf');
