<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container95joP32\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container95joP32/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container95joP32.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container95joP32\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container95joP32\App_KernelDevDebugContainer([
    'container.build_hash' => '95joP32',
    'container.build_id' => 'f504d482',
    'container.build_time' => 1618495120,
], __DIR__.\DIRECTORY_SEPARATOR.'Container95joP32');
