<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXzOCT67\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXzOCT67/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXzOCT67.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXzOCT67\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXzOCT67\App_KernelDevDebugContainer([
    'container.build_hash' => 'XzOCT67',
    'container.build_id' => 'ceaf233b',
    'container.build_time' => 1618857270,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXzOCT67');
