<?php

namespace ContainerUj5T7hK;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5pV4cQqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5pV4cQq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5pV4cQq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'products' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'products' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
